### ISSUE TITLE
If configuring staticPath as a subdirectory, no files are being copied

### ISSUE THREAD

**Issue by ceresith** [elwin013/parcel-reporter-static-files-copy#11] opened 2021-05-06 14:44 UTC
A configuration like the following doesn't work, attempting to copy files from a subdirectory. In this example, only the content of `real-static` should be copied, not the content of `static`). However, the plugin will create an empty `static` directory in the `dist` folder and not copy any files from `real-static`.

```
"staticFiles": {
	"staticPath": "static/real-static",
	"staticOutPath": "static"
},
```

To double-check the issue, I've replaced the copying functions of the plugin with functions of that I know they work, and that did solve the issue for me. So I assume the bug is somewhere inside `copyDir`/`recurseSync`. Maybe we could use some better tested copy functions instead.

**Comment by elwin013** [comment] 2021-05-07 12:26
Hey @ceresith.

Unfortunately I wasn't able to reproduce issue on the latest version (`1.3.0`), I've used this configuration (same as you copied above):

```
  "staticFiles": {
    "staticPath": "static/real-static",
    "staticOutPath": "static"
  }
```

with static folder tree like this:

```
static/
├── magic
│   └── magic.txt
├── real-static
│   └── kitten.jpg
└── static.txt
```

After run `parcel build src/index.html` I've got:

```
dist/
├── index.ccd12655.js
├── index.ccd12655.js.map
├── index.html
└── static
    └── kitten.jpg
```

which is expected output.

There is a chance that you're using some previous version which, in fact, could have some bug.

If problem occurs in latest version - let me know. It will be great if you could prepare some example.

Closing this issue (at least for now).

**Closed by elwin013** 2021-05-07 12:26 UTC

**Comment by bdube30** [comment] 2021-08-30 19:55
I got exactly the same issue describe by @ceresith .

When I have this :
```
"staticFiles": {
    "staticPath": "src/img/parcours",
    "staticOutPath": "img/parcours"
  }
```
  
  The `dist/img/parcours` folders are created, but no file are copiued into it.
  
  But if I do this : 
  ```
"staticFiles": {
    "staticPath": "src",
    "staticOutPath": "img/parcours"
  }
```

All the content of `src` folder is successfully copied into  `dist/img/parcours`.

I am using the 1.3.0 version of this plugin and the 2.0.0-rc.0 version of Parcel

**Comment by elwin013** [comment] 2021-09-07 09:04
Hello @bdube30,
unfortunately I cannot reproduce this issue. Using configuration like this

```
 "staticFiles": {
    "staticPath": "src/static/images",
    "staticOutPath": "vendor/subfolder"
  }
```

all files/directories from `src/static/images` are successfully copied into `dist/vendor/subfolder` as expected.

Can you provide some project where bug is reproduced?

**Comment by christianvoigt** [comment] 2021-09-08 14:31
Hi, I have the same issue as @ceresith and @bdube30 and can reproduce it in your "examples/customStaticFolder" example:

I simply changed the staticPath in the `package.json` from "customStatic" to "customStatic/magic":

```json
  "staticFiles": {
    "staticPath": "customStatic/magic"
  }
```

If I run "npm run serve" I would expect that I can then open "localhost:1234/magic.txt" in the browser. But instead the `index.html` is served ("Hello" instead of "asd" appears in the browser).

**Comment by elwin013** [comment] 2021-09-08 18:13
Hello @christianvoigt,
I've changed static path as you wrote in your comment and run `npm run serve` - everything works as expected - `http://localhost:1234/magic.txt` serves `magic.txt` correctly:

![image](https://user-images.githubusercontent.com/375909/132539848-dc7bf05e-1b2e-40bc-ab77-9971d1926db3.png)

If it shows index.html then probably previous version of Parcel is used (or at least previous dev server, which serves index when asset is not found in bundle graph, please see https://github.com/elwin013/parcel-reporter-static-files-copy/issues/10).

**Comment by christianvoigt** [comment] 2021-09-08 20:59
Thanks for your fast answer. I don't think that I am testing this with the wrong version. I simply cloned your repository, made the changes in `package.json` and ran "npm install" in the example folder. 

To make sure I just checked the `node_modules/parcel/package.json` and the version used is `parcel@2.0.0-rc.0`. By the way, I am testing this on Windows 10. 

Given that these simply steps are causing an issue at least on some systems, I think you should reopen this issue.

**Comment by christianvoigt** [comment] 2021-09-08 21:12
Another reason why I think this is not fixed by upgrading parcel is that I encountered this issue first when I was working with the latest nightly version of parcel in my own repository.
